# Generated by Django 6.0.1 on 2026-01-12 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('hq_location', models.CharField(blank=True, max_length=255, verbose_name='HQ Location')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_stub', models.BooleanField(default=True, verbose_name='Is Stub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('snapshot', models.JSONField(help_text='Full copy of Company fields at this time', verbose_name='Snapshot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='companies.company', verbose_name='Company')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_edits', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'verbose_name': 'Company Revision',
                'verbose_name_plural': 'Company Revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyWebsite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('label', models.CharField(blank=True, help_text='e.g. "Homepage", "Careers", "Blog"', max_length=50, verbose_name='Label')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Website',
                'verbose_name_plural': 'Company Websites',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.industry', verbose_name='Industry'),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('READ_ONLY', 'Read Only')], default='READ_ONLY', max_length=20, verbose_name='Role')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='companies.company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_company_user')],
            },
        ),
    ]
