# Generated by Django 6.0.1 on 2026-01-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(help_text="Unique identifier for this flag (e.g., 'new_checkout')", max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Whether this feature flag is currently enabled')),
                ('description', models.TextField(blank=True, help_text='Internal notes about this flag and what it controls')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
    ]
