# syntax=docker/dockerfile:1.19.0

ARG PYTHON_VERSION=3.13
ARG NODE_VERSION=24

FROM node:${NODE_VERSION}-alpine AS frontend-builder
WORKDIR /app
RUN corepack enable
COPY frontend ./frontend
WORKDIR /app/frontend/orgtorii
RUN pnpm install --frozen-lockfile
RUN pnpm build

FROM ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-bookworm-slim AS python-builder
WORKDIR /app
ENV UV_PROJECT_ENVIRONMENT=/app/.venv
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --python ${PYTHON_VERSION}

FROM python:${PYTHON_VERSION}-slim AS runtime
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DJANGO_SETTINGS_MODULE="orgtorii.settings" \
    PATH="/app/.venv/bin:$PATH"

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

COPY --from=python-builder /app/.venv /app/.venv
COPY orgtorii ./
COPY orgtorii/manage.py ./manage.py
COPY frontend/orgtorii/package.json ./frontend/orgtorii/package.json
COPY --from=frontend-builder /app/frontend/orgtorii/dist ./frontend/orgtorii/dist

RUN python manage.py collectstatic --noinput

EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "orgtorii.wsgi:application"]

