# Generated by Django 6.0.1 on 2026-01-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organisation'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organisation', 'status'], name='billing_sub_organis_e5be28_idx'),
        ),
    ]
