# Generated by Django 6.0.1 on 2026-01-07 12:47

import django.db.models.deletion
import meta.models
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="URL path for this page (e.g., 'about-us' becomes /about-us/)", max_length=200, unique=True, verbose_name='URL slug')),
                ('image', models.ImageField(blank=True, help_text='Used for Open Graph and social sharing', upload_to='pages/', verbose_name='Featured image')),
                ('is_published', models.BooleanField(default=False, help_text='Only published pages are visible to visitors', verbose_name='Published')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Optional: Schedule when this page becomes visible', null=True, verbose_name='Publish at')),
                ('unpublish_at', models.DateTimeField(blank=True, help_text='Optional: Schedule when this page is hidden', null=True, verbose_name='Unpublish at')),
                ('template_name', models.CharField(blank=True, help_text="Optional: Custom template path (e.g., 'pages/custom/pricing.html')", max_length=200, verbose_name='Template override')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Markdown content for the page', verbose_name='Content')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, verbose_name='Meta description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page Translation',
                'db_table': 'pages_page_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
